/* DO NOT EDIT, file generated by nestjs-i18n */

/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "common": {
        "exceptions": {
            "DuplicationException": {
                "message": string;
                "field": string;
            };
            "EntityNotFound": {
                "message": string;
            };
            "NonExistentEntity": {
                "message": string;
            };
        };
        "responses": {
            "EntityDeleted": {
                "message": string;
            };
            "EntityUpdated": {
                "message": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
